spring:
  application:
    name: rbnb

  datasource:
    url: jdbc:postgresql://localhost:5432/rbnb
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # This line has been updated
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
