spring:
  application:
    name: rbnb
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000  # a day in milliseconds
        refresh-token:
          expiration: 604800000  # 7 days in milliseconds

  datasource:
    url: jdbc:postgresql://localhost:5432/rbnb
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # This line keeps the JPA entities in sync with the DB schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0

  session:
    store-type: jdbc  # This configures Spring Session to use JDBC for session storage
    jdbc:
      initialize-schema: always  # This ensures the session tables are created automatically
